import os

# NOTE this path is also the default path for pyfn
DIR_DATA = "data/experiments/xp_001/data/"
DIR_MODELS = "data/models/"

# The files generated by pyfn
TRAIN_FILES = ["train.sentences", "train.frame.elements"]
DEV_FILES = ["dev.sentences", "dev.frames"]
TEST_FILES = ["test.sentences", "test.frames"]

ALL_FILES = [TRAIN_FILES, DEV_FILES, TEST_FILES]

for handle in ALL_FILES:
    handle[0] = os.path.join(DIR_DATA, handle[0])
    handle[1] = os.path.join(DIR_DATA, handle[1])

# NOTE model is actually saved in three individual files (.ph, .in_voc, .out_voc)
MODEL_NAME = "test"
SAVED_MODEL = os.path.join(DIR_MODELS, MODEL_NAME)
